const starTrekProductions = {
  "<start>": [
    "<character>"
  ],
  "<character>": [
    "The Enterprise <verb_singular>",
    "The Enterprise <verb_singular>",
    "The Enterprise <verb_singular>",
    "The Enterprise <verb_singular>",
    "The crew of the Enterprise <verb_singular>",
    "The crew of the Enterprise <verb_singular>",
    "The crew of the Enterprise <verb_singular>",
    "The crew of the Enterprise <verb_singular>",
    "An omnipotent being known as Q <verb_singular>",
    "Captain Picard and some of his crew <verb_plural>",
    "Wesley <verb_singular>",
    "Data <verb_singular>",
    "Data <verb_singular>",
    "Data <verb_singular>",
    "Data <verb_singular>",
    "Worf, Data and Riker <verb_plural>",
    "Counselor Troi <verb_singular>",
    "Counselor Troi <verb_singular>",
    "Counselor Troi <verb_singular>",
    "Riker, Troi, Data and Yar <verb_plural>",
    "La Forge <verb_singular>",
    "La Forge <verb_singular>",
    "La Forge <verb_singular>",
    "Worf <verb_singular>",
    "Worf <verb_singular>",
    "Worf <verb_singular>",
    "Dr. Crusher <verb_singular>",
    "Dr. Crusher <verb_singular>",
    "Dr. Crusher <verb_singular>",
    "Picard <verb_singular>",
    "Picard <verb_singular>",
    "Picard <verb_singular>",
    "Picard <verb_singular>",
    "Picard <verb_singular>",
    "Picard <verb_singular>",
    "Lt. Barclay <verb_singular>",
    "Q <verb_singular>",
    "Counselor Troi's mother <verb_singular>",
    "Captain Picard and Lt. Worf <verb_plural>",
    "Ensign Ro <verb_singular>",
    "Picard and Data <verb_plural>"
  ],
  "<verb_singular>": [
    "is exposed to <noun>",
    "must deal with <noun>",
    "is trapped on a planet with <noun>",
    "struggles to cope with <noun>",
    "is guided to a distant, long-dead world inhabited by <noun>",
    "is infected with a virus <ending_phrase_singular_things>",
    "makes a confrontational first contact with <noun>",
    "docks at a starbase for repairs <ending_phrase>",
    "searches for answers about <noun>",
    "encounters <noun>",
    "rescues <noun>",
    "comes across an Enterprise shuttlecraft adrift in space with an unconscious duplicate Capt. Picard inside",
    "responds to an apparent distress call from <noun>",
    "beams down to a planet ruled by <noun>",
    "transports an elderly Starfleet Admiral <ending_phrase>",
    "searches for answers about <noun>",
    "is held captive on a deserted planet by <noun>",
    "gets left behind on a storm-plagued planet <ending_phrase>",
    "pursues <noun>",
    "reaches out to <noun>",
    "gets trapped in a an energy-absorbing rupture in space <ending_phrase>",
    "is electrocuted through a shuttlecraft's computer <ending_phrase>",
    "is brainwashed by the Romulans to assassinate <noun>",
    "must learn to communicate with a race that speaks in metaphor <ending_phrase>",
    "tracks down <noun>",
    "follows Spock into Romulan space <ending_phrase>",
    "tries to save <noun>",
    "is accosted by <noun>"
  ],
  "<verb_plural>": [
    "are exposed to <noun>",
    "must deal with <noun>",
    "are trapped on a planet with <noun>",
    "struggle to cope with <noun>",
    "are caught in a deadly trap in the holodeck <ending_phrase>",
    "are guided to a distant, long-dead world inhabited by <noun>",
    "are infected with a virus <ending_phrase_singular_things>",
    "make a confrontational first contact with <noun>",
    "dock at a starbase for repairs <ending_phrase>",
    "search for answers about <noun>",
    "encounter <noun>",
    "rescue <noun>",
    "come across an Enterprise shuttlecraft adrift in space with an unconscious duplicate Capt. Picard inside",
    "respond to an apparent distress call from <noun>",
    "beam down to a planet ruled by <noun>",
    "transport an elderly Starfleet Admiral <ending_phrase>",
    "search for answers about <noun>",
    "are held captive on a deserted planet by <noun>",
    "are kidnapped by <noun>",
    "get trapped in a an energy-absorbing rupture in space <ending_phrase>",
    "are brainwashed by the Romulans to assassinate <noun>",
    "must decide where their priorities lie <ending_phrase>",
    "must stop the Romulans from helping their pawns achieve victory",
    "track down <noun>",
    "follow Spock into Romulan space <ending_phrase>",
    "try to save <noun>",
    "get caught in a time loop <ending_phrase>",
    "are accosted by <noun>"
  ],
  "<noun>": [
    "a mysterious cloud creature <ending_phrase_singular_things>",
    "a gigantic energy-draining space organism <ending_phrase_singular_things>",
    "the piratical Ferengi race <ending_phrase>",
    "a sentient entity <ending_phrase_singular_things>",
    "three cryogenically frozen people <ending_phrase_plural_persons>",
    "a mysterious void in space <ending_phrase_singular_things>",
    "the captain of a broken-down freighter <ending_phrase>",
    "an alien girl in distress <ending_phrase>",
    "a microscopic life form <ending_phrase_singular_things>",
    "a slick, black, oily, sentient and immortal puddle of evil",
    "a Klingon ship <ending_phrase>",
    "the superior technology of a very ancient race <ending_phrase_singular_things>",
    "an unknown alien ship <ending_phrase>",
    "a Federation colony <ending_phrase>",
    "an ancient yet effective trap left by an extinct race <ending_phrase_singular_things>",
    "an alien being",
    "a strange race from the future",
    "a deserted planet where a ship has crashed <ending_phrase>",
    "an unknown force <ending_phrase_singular_things>",
    "a gigantic galactic infant <ending_phrase_singular_things>",
    "a parasite <ending_phrase_singular_things>",
    "a Klingon governor",
    "the Crystalline Entity",
    "someone who claims to be a historian from the future",
    "an approaching alien ship <ending_phrase_singular_things>",
    "a long-lost ship <ending_phrase>",
    "potentially dangerous energy life form <ending_phrase_singular_things>",
    "a lone Borg drone, separated from the collective",
    "an archaeological secret that explains the predominance of humanoid life forms in the galaxy",
    "two scientists from a nearby planet <ending_phrase_plural_persons>"
  ],
  "<ending_phrase>": [
    "while involved in a dispute between feuding worlds",
    "as the result of a ship-wide scan from an alien race",
    "where they break the Prime Directive",
    "where they encounter the Borg for the first time",
    "in the hopes of locating a missing freighter crew",
    "to negotiate a hostage crisis",
    "and nothing is as simple as it seems",
    "while assigned to investigate missing outposts in the Neutral Zone",
    "to negotiate an end to a civil war",
    "while Wesley commands his first team",
    "while Picard is away for routine surgery",
    "where a mission costs the life of a crew member",
    "while dangers lurk among them",
    "and only Guinan knows why",
    "and meanwhile Picard is replaced with a replica as impostor captain",
    "in search of a dangerous weapon",
    "while Wesley's latest science project escapes the lab",
    "where an interesting figure awaits",
    "after being fired upon by a Cardassian vessel",
    "while answering a distress call",
    "after passing through a wormhole",
    "where all but Data, Troi and Guinan experience rising hallucinations and paranoia",
    "when assigned to investigate an unknown probe",
    "as the Klingon Empire descends into a bitter civil war",
    "under a difficult set of circumstances",
    "on a dangerous mission",
    "after an asteroid wreaks havoc of catastrophic proportions",
    "with a few extra surprises",
    "as undetectable parasites devour the ship",
    "as the Enterprise deals with the installation of a new warp core that won't work as expected",
    "while searching for a missing Federation medical transport",
    "as the Enterprise's computer begins to become self-aware"
  ],
  "<ending_phrase_singular_persons>": [
    "<ending_phrase>",
    "<ending_phrase>",
    "<ending_phrase>",
    "<ending_phrase>",
    "<ending_phrase>",
    "<ending_phrase>",
    "<ending_phrase>",
    "who threatens the galaxy",
    "who was found aboard a wayward derelict Earth vessel",
    "who is under attack",
    "who is trying to transform them into another species",
    "who wipes their memory",
    "who is suffering from a delusion of being a starship captain",
    "who claims that cumulative exposure to warp energy is weakening the fabric of space"
  ],
  "<ending_phrase_plural_persons>": [
    "<ending_phrase>",
    "<ending_phrase>",
    "<ending_phrase>",
    "<ending_phrase>",
    "<ending_phrase>",
    "<ending_phrase>",
    "<ending_phrase>",
    "who threaten the galaxy",
    "who were found aboard a wayward derelict Earth vessel",
    "who wipe their memory",
    "who are not what they appear to be",
    "who claim that cumulative exposure to warp energy is weakening the fabric of space",
  ],
  "<ending_phrase_singular_things>": [
    "<ending_phrase>",
    "<ending_phrase>",
    "<ending_phrase>",
    "<ending_phrase>",
    "<ending_phrase>",
    "<ending_phrase>",
    "<ending_phrase>",
    "which rapidly ages them",
    "that threatens the galaxy",
    "that causes them to behave as though they were intoxicated",
    "that envelops them",
    "which triggers an epidemic of rapid aging",
    "which is responsible for the death of an engineer",
    "which the crew strugges to cope with",
    "which creates system malfunctions for the Enterprise",
    "that is under attack",
    "that drains the Enterprise's energy",
    "that is trying to transform them into another species",
    "that wipes their memory"
  ],
  "<ending_phrase_plural_things>": [
    "<ending_phrase>",
    "<ending_phrase>",
    "<ending_phrase>",
    "<ending_phrase>",
    "<ending_phrase>",
    "<ending_phrase>",
    "<ending_phrase>",
    "that threaten the galaxy",
    "which trigger an epidemic of rapid aging",
    "which are responsible for the death of an engineer",
    "which the crew strugges to cope with",
    "which create system malfunctions for the Enterprise",
    "which wipes their memory"
  ]
};

export default starTrekProductions;
